name: Make sure PRs target the develop branch

on:
  pull_request_target:

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR branch
        if: github.event.pull_request.base.ref == 'master'
        run: |
          echo "Please do not submit against `master`, use `develop` instead"
          exit 1
