name: Pre-Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Increment version
        run: |
          cd testextension
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          npm version patch
          git push
      # - name: Create pre-release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     prerelease: true
      #     generate_release_notes: true
      #     body: "> **Note: This is a pre-release, so may contain more bugs**"
